# Generated by Django 5.2.4 on 2025-07-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_remove_orderitem_user_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('starter', 'Starter'), ('fastfood', 'Fast Food'), ('main', 'Main Course'), ('dessert', 'Dessert'), ('drink', 'Drink')], default='main', max_length=20),
        ),
    ]
